apiVersion: apps/v1
kind: Deployment
metadata:
  name: gha-python-deployment
  labels:
    app: gha-python
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gha-python
  template:
    metadata:
      labels:
        app: gha-python
    spec:
      containers:
      - name: gha-python-container
        image: thethymca/gha-python-image-app:v1
        ports:
        - containerPort: 5000
        env:
          # Load the ConfigMap keys
          - name: CAR
            valueFrom: 
              configMapKeyRef:
                name: test-configmap
                key: car
          - name: COUNTRY
            valueFrom:
              configMapKeyRef:
                name: test-configmap
                key: countr
